# Generated by go2rpm 1.11.1
%bcond_without check
%global debug_package %{nil}

# https://github.com/SherClockHolmes/webpush-go
%global goipath         github.com/SherClockHolmes/webpush-go
Version:                1.3.0

%gometa -L -f

%global common_description %{expand:
Web Push API Encryption with VAPID support.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           golang-github-sherclockholmes-webpush
Release:        %autorelease
Summary:        Web Push API Encryption with VAPID support

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Jun 22 2024 Scott R. Shinn <scott@atomicrocketturtle.com> - 1.3.0-1
- Initial package
